### ISSUE TITLE
UX BUG: Handle mismatched class labels in confusion_matrix

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-sample-classifier#118]
Mismatched IDs in the new visualizations can happen because the predictions are divorced from the plotting. For example, using the ecam dataset, I fit a regressor using the `month_of_life` column, but then attempted to plot using the `sex` column as the source of truth, yielding this less-than-great traceback:

```bash
Traceback (most recent call last):
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/internals.py", line 4857, in create_block_manager_from_blocks
    placement=slice(0, len(axes[0])))]
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/internals.py", line 3205, in make_block
    return klass(values, ndim=ndim, placement=placement)
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/internals.py", line 125, in __init__
    '{mgr}'.format(val=len(self.values), mgr=len(self.mgr_locs)))
ValueError: Wrong number of items passed 871, placement implies 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/q2cli/commands.py", line 274, in __call__
    results = action(**arguments)
  File "<decorator-gen-401>", line 2, in confusion_matrix
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 231, in bound_callable
    output_types, provenance)
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 424, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/classify.py", line 236, in confusion_matrix
    plot_title='confusion matrix')
  File "/Users/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/utilities.py", line 486, in _plot_accuracy
    palette=palette)
  File "/Users/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/utilities.py", line 446, in _predict_and_plot
    y_test, y_pred, classes, normalize=True, palette=palette)
  File "/Users/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/visuals.py", line 230, in _plot_confusion_matrix
    predictions = pd.DataFrame(cm, index=classes, columns=classes)
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/frame.py", line 379, in __init__
    copy=copy)
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/frame.py", line 536, in _init_ndarray
    return create_block_manager_from_blocks([values], [columns, index])
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/internals.py", line 4866, in create_block_manager_from_blocks
    construction_error(tot_items, blocks[0].shape[1:], axes, e)
  File "/Users/matthew/.conda/envs/q2dev/lib/python3.5/site-packages/pandas/core/internals.py", line 4843, in construction_error
    passed, implied))
ValueError: Shape of passed values is (871, 871), indices imply (2, 2)

Plugin error from sample-classifier:

  Shape of passed values is (871, 871), indices imply (2, 2)

See above for debug info.
```

Visualizers worth looking at w.r.t. this issue:

- scatterplot
- confusion-matrix

Maybe more?

**Comment by nbokulich** [comment]
this is actually an issue with mismatched dimensions — truth and predicted have a different # of classes (forget that the labels mismatch 100%!)

This is only an issue for confusion-matrix — scatterplot is not impacted.

need to validate that labels overlap to confirm that the same metadata column was passed.

what to do in cases of partial overlap? e.g., classifier is trained on a dataset of dog pics with class "pic of peanut" (labels: [y, n]). Use to classify several pics, for all of which true label == y. Some are classified as "n". Resulting heatmap would have dimensions (1, 2)

I'm not sure how common that scenario might occur, but we need to handle appropriately (plot empty row)
