### ISSUE TITLE
scatterplot/confusion matrix need to accept only regressor/classifier predictions, respectively

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-sample-classifier#119]
see error in #118 (@thermokarst was training a regressor, then viewing accuracy with confusion matrix)

for confusion matrix this is a bug and need to check. For scatterplot could either check inputs or just produce a more coherent error message (see below)

check that input data is appropriate type

example of attempting to view classifier results with scatterplot:
Command:
```
qiime sample-classifier scatterplot \
  --i-predictions mov-pics-BodySite-predictions-ncv.qza \
  --m-truth-file mov-pics-sample-metadata.tsv \
  --m-truth-column Year \
  --p-missing-samples ignore \
  --o-visualization moving-pictures-BodySite-predictions-mcv-scatter.qzv
```
Error:
```
  File "pandas/_libs/src/inference.pyx", line 1152, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "gut"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nbokulich/miniconda3/envs/qiime2-2018.4.1.dev/lib/python3.5/site-packages/q2cli/commands.py", line 274, in __call__
    results = action(**arguments)
  File "<decorator-gen-297>", line 2, in scatterplot
  File "/Users/nbokulich/miniconda3/envs/qiime2-2018.4.1.dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 232, in bound_callable
    output_types, provenance)
  File "/Users/nbokulich/miniconda3/envs/qiime2-2018.4.1.dev/lib/python3.5/site-packages/qiime2/sdk/action.py", line 429, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/nbokulich/Desktop/projects/q2-sample-classifier/q2_sample_classifier/classify.py", line 224, in scatterplot
    predictions = pd.to_numeric(predictions)
  File "/Users/nbokulich/miniconda3/envs/qiime2-2018.4.1.dev/lib/python3.5/site-packages/pandas/core/tools/numeric.py", line 133, in to_numeric
    coerce_numeric=coerce_numeric)
  File "pandas/_libs/src/inference.pyx", line 1185, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "gut" at position 0
```

**Comment by nbokulich** [comment]
current fix:
* scatterplot: predictions that cannot be cast to numeric fail (we cast to numeric at the start anyway, so this is a very convenient validation)
* confusion matrix: predictions must overlap with true labels (minimum 1 shared label)

The latter is not perfect (users could still input regressor results that happen to overlap with categorical data values), but it is functional. It may be more q2-friendly to make separate `Predictions[Numeric]` and `Predictions[Categorical]` types (instead of `SampleData[Predictions]`), but then we need a lot of code duplication:
* `predict` becomes `predict-regressor` and `predict-classifier` (identical methods! different i/o)
* `SampleEstimator` becomes `SampleClassifier` and `SampleRegressor` (identical types!)

so I really prefer the current fix but let me know if this is too lazy.

**Comment by thermokarst** [comment]
cc @ebolyen

**Comment by ebolyen** [comment]
Let's go with the duplication for now then! I'll just push TypeMap up on my priority list. Hopefully it'll be address with the transformer overhaul, but who knows.
