### ISSUE TITLE
ROC Curves bubbles up a confusing sklearn error message

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-sample-classifier#171]
**Bug Description**

While attempting to create test data for https://github.com/qiime2/q2-sample-classifier/issues/143, I ran into a cryptic error message when running `confusion-matrix`:

```bash
Plugin error from sample-classifier:

  Found input variables with inconsistent numbers of samples: [42, 77]
```

**Test data**

- Metadata: [moving-pictures-sample-metadata.txt](https://github.com/qiime2/q2-sample-classifier/files/3511032/moving-pictures-sample-metadata.txt)
- [Table](https://docs.qiime2.org/2019.7/tutorials/sample-classifier/#predicting-categorical-sample-data)

**Steps to reproduce the behavior**

```bash
qiime sample-classifier split-table \
  --i-table moving-pictures-table.qza \
  --m-metadata-file moving-pictures-sample-metadata.txt \
  --m-metadata-column nonsense \
  --p-no-stratify \
  --o-training-table training-table.qza \
  --o-test-table test-table.qza

qiime sample-classifier fit-classifier \
  --i-table training-table.qza \
  --m-metadata-file moving-pictures-sample-metadata.txt \
  --m-metadata-column nonsense \
  --o-sample-estimator estimator.qza \
  --o-feature-importance importance.qza

qiime sample-classifier predict-classification \
  --i-table test-table.qza \
  --i-sample-estimator estimator.qza \
  --o-predictions predictions.qza \
  --o-probabilities probabilities.qza

qiime sample-classifier confusion-matrix \
  --i-predictions predictions.qza \
  --i-probabilities probabilities.qza \
  --m-truth-file moving-pictures-sample-metadata.txt \
  --m-truth-column nonsense \
  --o-visualization never-get-here.qzv \
  --verbose
```

```bash
/home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)
/home/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/visuals.py:118: RuntimeWarning: invalid value encountered in true_divide
  cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
Traceback (most recent call last):
  File "/home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/decorator.py:decorator-gen-202>", line 2, in confusion_matrix
  File "/home/matthew/src/qiime2/qiime2/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/home/matthew/src/qiime2/qiime2/qiime2/sdk/action.py", line 445, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/home/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/classify.py", line 363, in confusion_matrix
    plot_title='confusion matrix')
  File "/home/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/utilities.py", line 493, in _plot_accuracy
    roc = _generate_roc_plots(truth, probabilities, palette)
  File "/home/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/visuals.py", line 198, in _generate_roc_plots
    binarized_targets, probabilities, fpr, tpr, roc_auc)
  File "/home/matthew/src/qiime2/q2-sample-classifier/q2_sample_classifier/visuals.py", line 268, in _roc_micro_average
    binarized_targets.ravel(), probabilities.ravel())
  File "/home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 622, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/sklearn/metrics/ranking.py", line 398, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "/home/matthew/.conda/envs/q2dev/lib/python3.6/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [42, 77]

Plugin error from sample-classifier:

  Found input variables with inconsistent numbers of samples: [42, 77]

See above for debug info.
```

**Expected behavior**
I have no clue what the error message is attempting to convey, I suspect it has something to do with the fact that I didn't stratify my samples, but, who knows.

**Comment by nbokulich** [comment]
> I suspect it has something to do with the fact that I didn't stratify my samples

Good call, it does. The issue is that you are not stratifying and have rare class labels, so when it comes to the ROC curves we are missing some classes in the `predictions`.  This is not a bug that is likely to surface frequently — really only if someone tests on a little toy dataset or a dataset with a ridiculous number of class labels and they do not stratify.

Should be an easy fix, though — will take a look tonight
